"""多视角融合（multiview）—— 两级球场坐标系、融合运行实体、时间轴、关联、质量、融合与全局滤波。

P0 范围：仅 axis-preserving（保轴）标定视角；只做二维球员球场位置的协同感知，
不碰 3D Pose、3D 球轨迹与跨视角 ReID。
"""

from app.vision.multiview.artifact import (
    FUSED_DIAGNOSTICS_FILENAME,
    FUSED_DIAGNOSTICS_SCHEMA_VERSION,
    FUSED_TRAJECTORY_FILENAME,
    FUSED_TRAJECTORY_SCHEMA_VERSION,
    build_fused_artifact,
    build_fusion_diagnostics,
    load_fused_artifact,
    serialize_fused_sample,
    write_fused_artifact,
    write_fusion_diagnostics,
)
from app.vision.multiview.association import (
    CrossViewPlayerAssociator,
    PlayerAssociation,
    min_cost_matching,
)
from app.vision.multiview.canonical_timeline import CanonicalTimelineBuilder
from app.vision.multiview.consumers import (
    FusedTrackPoint,
    TrajectorySource,
    metric_eligibility_policy,
    movement_points,
    select_trajectory_source,
    visualization_points,
)
from app.vision.multiview.court_frame import (
    AXIS_PRESERVING_VIEW_TYPES,
    CANONICAL_COURT_FRAME_SEMANTICS,
    COURT_LENGTH_FT,
    COURT_WIDTH_FT,
    LOCAL_COURT_FRAME_SEMANTICS,
    CanonicalCourtFrameDefinition,
    CourtOrientation,
    CourtOrientationLiteral,
    canonical_court_frame_path,
    canonical_to_local,
    is_supported_orientation_scope,
    load_canonical_court_frame,
    local_to_canonical,
    resolve_or_create_canonical_court_frame,
    validate_canonical_court_frame_compatibility,
    write_canonical_court_frame,
)
from app.vision.multiview.fusion import (
    FusionConfig,
    FusionMeasurement,
    FusionStatus,
    MeasurementSource,
    fuse_observation,
)
from app.vision.multiview.fusion_run import (
    MultiViewFusionRun,
    RunEligibility,
    RunStatus,
    default_run_output_dir,
)
from app.vision.multiview.global_filter import GlobalTrackFilter, predictions_for
from app.vision.multiview.pipeline import FusionPipelineResult, run_fusion_pipeline
from app.vision.multiview.pairing import (
    FramePairingDecision,
    FramePairingPlan,
    PairingStatus,
    build_frame_pairing_plan,
    observations_by_source_frame,
)
from app.vision.multiview.quality import (
    FOOTPOINT_METHOD_QUALITY,
    NORMALIZED_BBOX_REFERENCE,
    TRACKING_STATUS_QUALITY,
    IntrinsicFeatures,
    PairConsistencyResult,
    fusion_weights,
    intrinsic_from_canonical,
    normalized_bbox_score,
    pair_consistency,
    view_intrinsic_quality,
)
from app.vision.multiview.spike_adapter import (
    RENDER_SCHEMA_VERSION,
    RENDER_SOURCE_INTERPOLATED,
    RENDER_SOURCE_OBSERVED,
    SpikeAdapterError,
    canonicalize_view_observations,
    extract_render_observations,
    load_render_payload,
    load_view_observations,
)
from app.vision.multiview.sync import (
    SYNC_CALIBRATION_SCHEMA_VERSION,
    MultiViewSyncCalibration,
    SyncAuthorityIssue,
    SyncAuthorityValidation,
    SyncGateDecision,
    evaluate_sync_gate,
    load_sync_calibration,
    validate_sync_authority,
)
from app.vision.multiview.types import (
    CanonicalObservation,
    CanonicalTimelineTick,
    ViewAvailability,
    ViewObservation,
)
from app.vision.multiview.view_input import MultiViewViewInput

__all__ = [
    "AXIS_PRESERVING_VIEW_TYPES",
    "CANONICAL_COURT_FRAME_SEMANTICS",
    "LOCAL_COURT_FRAME_SEMANTICS",
    "COURT_LENGTH_FT",
    "COURT_WIDTH_FT",
    "CanonicalCourtFrameDefinition",
    "CanonicalObservation",
    "CanonicalTimelineBuilder",
    "CanonicalTimelineTick",
    "CourtOrientation",
    "CourtOrientationLiteral",
    "CrossViewPlayerAssociator",
    "FUSED_DIAGNOSTICS_FILENAME",
    "FUSED_DIAGNOSTICS_SCHEMA_VERSION",
    "FUSED_TRAJECTORY_FILENAME",
    "FUSED_TRAJECTORY_SCHEMA_VERSION",
    "FOOTPOINT_METHOD_QUALITY",
    "FusionConfig",
    "FusionMeasurement",
    "FusionPipelineResult",
    "FramePairingDecision",
    "FramePairingPlan",
    "FusionStatus",
    "FusionConfig",
    "FusionMeasurement",
    "FusedTrackPoint",
    "GlobalTrackFilter",
    "IntrinsicFeatures",
    "MeasurementSource",
    "MultiViewFusionRun",
    "MultiViewSyncCalibration",
    "SyncAuthorityIssue",
    "SyncAuthorityValidation",
    "MultiViewViewInput",
    "NORMALIZED_BBOX_REFERENCE",
    "PairConsistencyResult",
    "PairingStatus",
    "PlayerAssociation",
    "RENDER_SCHEMA_VERSION",
    "RENDER_SOURCE_INTERPOLATED",
    "RENDER_SOURCE_OBSERVED",
    "RunEligibility",
    "RunStatus",
    "SYNC_CALIBRATION_SCHEMA_VERSION",
    "SpikeAdapterError",
    "SyncGateDecision",
    "TRACKING_STATUS_QUALITY",
    "TrajectorySource",
    "ViewAvailability",
    "ViewObservation",
    "build_fused_artifact",
    "build_frame_pairing_plan",
    "build_fusion_diagnostics",
    "canonical_to_local",
    "canonical_court_frame_path",
    "canonicalize_view_observations",
    "default_run_output_dir",
    "evaluate_sync_gate",
    "validate_sync_authority",
    "extract_render_observations",
    "fusion_weights",
    "fuse_observation",
    "intrinsic_from_canonical",
    "is_supported_orientation_scope",
    "load_canonical_court_frame",
    "load_fused_artifact",
    "load_render_payload",
    "load_sync_calibration",
    "load_view_observations",
    "local_to_canonical",
    "metric_eligibility_policy",
    "min_cost_matching",
    "movement_points",
    "observations_by_source_frame",
    "normalized_bbox_score",
    "pair_consistency",
    "predictions_for",
    "resolve_or_create_canonical_court_frame",
    "validate_canonical_court_frame_compatibility",
    "run_fusion_pipeline",
    "select_trajectory_source",
    "serialize_fused_sample",
    "view_intrinsic_quality",
    "visualization_points",
    "write_canonical_court_frame",
    "write_fused_artifact",
    "write_fusion_diagnostics",
]
